#! /bin/bash

#zinud Login-configurator script, per-user ZinuD desktop init & configuration

# +------------------------------------------------------------+
# | mermouy@gmail.com
# |
# | This program is free software; you can redistribute it and/or
# | modify it under the terms of the GNU General Public License
# | as published by the Free Software Foundation; either version
# | 3 of the License, or (at your option) any later version.
# | 
# | This program is distributed in the hope that it will be useful,
# | but WITHOUT ANY WARRANTY; without even the implied warranty
# | of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# | See the GNU General Public License for more details.
# |
# | You should have received a copy of the GNU General Public
# | License along with this program; if not, write to the
# | Free Software Foundation, Inc., 51 Franklin St,
# | Fifth Floor, Boston, MA  02110-1301  USA
# +------------------------------------------------------------+



# VARIABLES
zinrep="/usr/share/zinud/zinud"
tempdiag="/tmp/tmpdiag"
utilisateur="$1"

# Vérification du lancement par root
if [[ $EUID -ne 0 ]]; then
	zenity --error --title="$Su" --text="$Sutxt $Rerunnow" --window-icon="$Zinicon"
	gksu exec $0
	exit 0
fi

### On source le fichier de langue ###

. ~/.config/zinud-install/lang.cfg

		########        Fonctions       ########

function Modconnect {
dialog --backtitle "Zinud Desktop Install" --title "Session" --ok-label "Valider" --cancel-label "Quitter" --radiolist "Comment souhaitez vous vous connecter à votre session?\nUtilisez les flèches et la barre espace." 13 70 4\
  "nits" "Ne rien faire du tout" off\
  "stax" "Démarrage avec identification en mode texte (conseillé)" on 2>$tempdiag  
  CONNEXION=`cat $tempdiag`
  case $CONNEXION in
  nits) Nits ;;
  stax) Stax ;;
  esac
  }

#Fonction aucune action
function Nits (){
dialog --msgbox "Pour lancer le bureau ZinuD exécutez:\n\nzinud-start\n\nune fois connecté dans une console X." 10 55
}

# Installation Gdm
function Gdm (){
if [ -e /etc/init.d/gdm ]
then
	if [ -e /home/$utilisateur/.xinitrc ]
	then
		mv -v /home/$utilisateur/.xinitrc /home/$utilisateur/.xinitrc~
    	fi
	cp -vf $zinrep/xinitrc /home/$utilisateur/.xinitrc
	update-rc.d -f gdm defaults
	dialog --msgbox "Vous pouvez relancer ce script à tout moment\nen lancant en root la commande:\n\nlogin-configurator <utilisateur>\n\n" 12 45
else
dialog --msgbox "Vous devez installer le paquet 'gdm' pour utiliser cette fonctionnalité,\n" 12 45
	aptitude install gdm
	Gdm
fi
}
  
  # Installation autostartx
function Stax (){
cd /home/$utilisateur
if [ -f .profile ]
then
	mv -v .profile .profile~
fi
cp -vf $zinrep/profile .profile
if [ -e /home/$utilisateur/.xinitrc ]
then
	mv -v /home/$utilisateur/.xinitrc /home/$utilisateur/.xinitrc~
fi
cp -vf $zinrep/xinitrc /home/$utilisateur/.xinitrc
update-rc.d -f gdm remove
dialog --msgbox "Auto Start X installé et configuré!\n\nVous pouvez relancer ce script à tout moment en lancant en root la commande:\n\nlogin-configurator <utilisateur>\n\n" 12 45
}
  
  # Installation autologin
function Auto (){
    # Autologin
	cd $zinrep
	sed -e "s/user/$utilisateur/g" autologinud > autologin.c
	gcc -o autologin autologin.c
	mv autologin /usr/local/sbin/
	chmod u+x /usr/local/sbin/autologin
	cd /etc/
	cp -vf inittab inittab~
	sed -e "s:/sbin/getty 38400 tty1:/bin/login -f $utilisateur tty1 </dev/tty1 >/dev/tty1 2>&1:g" inittab > inittabtemp
	mv -v inittabtemp inittab
	dialog --msgbox "Connexion automatique installée et configurée!" 12 45
    # Autostartx
    Stax
}
		#######   Fin des déclaration des fonctions   #######

# Vérification de l'entrée utilisateur
Userlistexist=$(cat /etc/passwd | cut -d: -f1 | grep $1)		  
if [ $utilisateur = "root" ]
then
dialog  --title "Configuration initiale" --inputbox "Entrez un utilisateur existant mais pas root\!:"  10 45 2>$tempdiag
	utilisateur=`cat $tempdiag`
	exec $0 $utilisateur
elif [ -d /home/$utilisateur/ ] && [ ! -z $Userlistexist ]
then

# Choix du mode de connexion
	Modconnect
	if [ -e $tempdiag ]
	then
		rm $tempdiag
	fi
	exit 0
	
#Si utilisateur non-existant
else
	dialog --title "Configuration initiale" --inputbox "L'utilisateur sélectionné n'existe pas! Entrez un utilisateur existant:	" 12 45 2>$tempdiag
	utilisateur=`cat $tempdiag`
	exec $0 $utilisateur
fi
