#!/bin/bash
#version 0.1.1

#VARIABLES
zinrep="/usr/share/zinud"

#control install
if [ "$1" = "" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then  
  echo "###################################################"
  echo "###    Il manque un argument à la commande!     ###"
  echo "###################################################"
  echo ""
  echo "zinud-install -h : cette aide"
  echo "zinud-install -i : installation zinud-desktop (!!Non-free!!)"
  echo "zinud-install -b : installation de zinud-base uniquement  (!!Non-free!!)"
  echo "zinud-install -f : installation zinud-full  (non disponible)"
  echo "zinud-install -s : modification sources.list uniquement"
  exit 0
fi

   #FONCTIONS

function sources (){
wget http://rep.zinud.youm.org/sources.list
mv /etc/apt/sources.list /etc/apt/sources.list-backup
mv sources.list /etc/apt/sources.list
}

function clefs () {
wget -q http://repository.glx-dock.org/cairo-dock.gpg -O- | apt-key add -
aptitude update
aptitude -y install unzip debian-multimedia-keyring
aptitude update
}

function smxinstall () {
cd /usr/local/bin/
wget -Nc smxi.org/smxi.zip
unzip smxi.zip
rm smxi.zip
cd
}

if [ "$1" = "-i" ] 
then
	cd
	sources
	clefs
	smxinstall
	smxi
	aptitude -y install zinud-base zinud-desktop zinud-fonts flashplugin-nonfree
elif [ "$1" = "-b" ] 
then
	cd
	sources
	clefs
	smxinstall
	smxi
	aptitude -y install zinud-base zinud-fonts flashplugin-nonfree
elif [ "$1" = "-s" ]
then
	cd
	sources
	clefs
elif [ "$1" = "-f" ]
then
	echo "###############################################################################"
	echo "###          Mais puisqu'on vous dit que c'est pas encore dispo!!!          ###"
	echo "###############################################################################"
	exit 0
#sortie en erreur
else
	echo "###############################################################################"
	echo "###   Zinud ne peut s'installer pour une raison inconnue et myterieuse...   ###"
	echo "###############################################################################"
fi
